In [ ]:
import torch

In [2]:
print(torch.__version__)

1.13.1


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim #How many dimensions

1

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                     [9,10]])

In [11]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [15]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0,2,0]

tensor(7)

In [54]:
PracticeTensor = torch.tensor([[[1,11,111],
                                [2,22,222],
                                [3,33,333]],
                              
                              [ [4,44,444],
                                [5,55,555],
                                [6,66,666]],
                               
                              [ [7,77,777],
                                [8,88,888],
                                [9,99,999]],
                              
                               [ [7,77,777],
                                [8,88,888],
                                [9,99,999]]])

In [55]:
PracticeTensor.ndim

3

In [51]:
PracticeTensor[1,0,2]

tensor(444)

In [56]:
PracticeTensor.size()

torch.Size([4, 3, 3])

### Random Tensors

These are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data. BIG CONCEPT

'Start with random numbers .-> look at data -> update random numbers -> look at data -> update random numbers'


In [75]:
random_tensor = torch.rand(1,3,4)

In [74]:
random_tensor.dim()

4

In [77]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size =(224,224,3)) # height, width, color, channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [78]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)

In [81]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [83]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensors and tensors-like

In [98]:
one_to_ten = torch.arange(1,11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
# Creating a tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)

In [102]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
torch.zeros_like()

# Tensor datatypes

In [134]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None, # what dataype is your tensor 
                              device = "cuda", #device default is cpu
                              requires_grad = False) # whether or not to track gradients

NameError: name 'float16' is not defined

In [120]:
float_32_tensor.dtype

torch.float32

In [121]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [122]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

# Getting information from tensors

In [139]:
some_tensor = torch.rand(3,4,
                        dtype = torch.float64,
                        device = "cuda")
some_tensor

tensor([[0.5282, 0.9403, 0.9300, 0.0347],
        [0.8754, 0.4330, 0.8373, 0.2608],
        [0.1864, 0.0201, 0.5699, 0.2804]], device='cuda:0',
       dtype=torch.float64)

In [140]:
# Finding out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Devise tensor is on: {some_tensor.device}")

tensor([[0.5282, 0.9403, 0.9300, 0.0347],
        [0.8754, 0.4330, 0.8373, 0.2608],
        [0.1864, 0.0201, 0.5699, 0.2804]], device='cuda:0',
       dtype=torch.float64)
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Devise tensor is on: cuda:0


# Manipulating Tensors (tensor operations)

In [152]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [150]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [153]:
#subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try out PyTorch in-built functions


torch.mul(tensor, 10)

In [155]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix multiplication

In [156]:
# Element wise multiplication

print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor} ")
# but this is an element wise multiplication? This isn't matrix multiplication

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9]) 


In [157]:
#Matrix Multiplciation

torch.matmul(tensor, tensor)

tensor(14)

In [158]:
# Matrix multiplication by hand
1 * 1 + 2*2 + 3*3

14

In [161]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 1e+03 µs


tensor(14)

In [162]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [168]:
practice = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [169]:
torch.matmul(practice,practice)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [170]:
tensor @ tensor

tensor(14)

In [171]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.4106, 1.1242],
        [0.2382, 0.5487]])

In [173]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.mm(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [175]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [174]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
x = torch.arange

# Finding values from the Torch tensors

In [178]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [180]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [181]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [184]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [185]:
torch.sum(x)

tensor(450)

In [190]:
torch.argmax(x)

tensor(9)

In [191]:
x[9]

tensor(90)

# Reshaping , stacking, squeezing and unsqueezing tensors

In [238]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [239]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x, x_reshaped, x_reshaped.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [200]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x, x_reshaped, x_reshaped.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# You can do any shape it looks like

In [203]:
x = torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [205]:
# Add an extra dimension
x_reshaped = x.reshape(2,6)
x, x_reshaped, x_reshaped.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([2, 6]))

In [209]:
# Change the view
z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [210]:
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [225]:
# Stack tensors on top of each other
x_stacked_only = torch.stack([x,x,x,x])
x_stacked_0 = torch.stack([x,x,x,x], dim = 0)
x_stacked_1 = torch.stack([x,x,x,x], dim = 1)

x, x_stacked_only, x_stacked_0, x_stacked_1

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.],
         [11., 11., 11., 11.],
         [12., 1

In [229]:
x_vstack = torch.vstack([x,x,x,x])
x_hstack = torch.hstack([x,x,x,x])
x_vstack, x_hstack

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  5.,  2.,
          3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  5.,  2.,  3.,  4.,
          5.,  6.,  7.,  8.,  9., 10., 11., 12.,  5.,  2.,  3.,  4.,  5.,  6.,
          7.,  8.,  9., 10., 11., 12.]))

# Squeeze and unsqueeze

In [240]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [241]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [253]:
# torch.squeeze() - removes all single dimensions from a target tensor
x = torch.arange(1,10)
x_reshaped = x.reshape(1,9)
x_squeezed = x_reshaped.squeeze()
print(f"Original tensor: {x}, with shape {x.shape}")
print(f"What it looks like reshaped: {x_reshaped }, The shape being: {x_reshaped.shape}")
print(f"What it looks like squeezed: {x_reshaped.squeeze()}, The shape being: {x_reshaped.squeeze().shape} " )
# single dimensions are removed

Original tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), with shape torch.Size([9])
What it looks like reshaped: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), The shape being: torch.Size([1, 9])
What it looks like squeezed: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), The shape being: torch.Size([9]) 


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimensions)

In [259]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension wiht unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
New shape: torch.Size([9, 1])


In [264]:
# torch.permute
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
# make the color to be the 0th dimension - So we want: [color_channel, height, width]

x_permuted = x_original.permute(2,0,1)
x_permuted.shape



torch.Size([3, 224, 224])

In [266]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [275]:
x[0][2][2]

tensor(9)

In [284]:
# Get all values of 0th and 1st dimensions but only index 1 of second dimension
x[:,:,2]

tensor([[3, 6, 9]])

In [285]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [286]:
# Get index 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [292]:
# Index on x to get return 9
x[:,2,2]

tensor([9])

In [289]:
# Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

In [293]:
import torch
import numpy as np

In [295]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [296]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [297]:
array = array + 1

In [299]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [301]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# GPU STUFF

In [302]:
!nvidia-smi

Mon Dec 26 12:36:14 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.41       Driver Version: 527.41       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:2B:00.0  On |                  N/A |
|  0%   36C    P8    36W / 370W |   2624MiB / 12288MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [303]:
# checking for gpu access by PyTorch
torch.cuda.is_available()

True

In [304]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [305]:
device

'cuda'

In [306]:
torch.cuda.device_count()

1

# Putting tensors (and models) on the GPU
GPU's are faster 

In [307]:
tensor = torch.tensor([1,2,3], device = "cuda")

In [312]:
torch.tensor([1,2,3]).cuda()

tensor([1, 2, 3], device='cuda:0')

In [308]:
tensor.device

device(type='cuda', index=0)